os: linux
dist: trusty
language: python
services: docker

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  # Always rebuild
  - 'docker build --tag x11vnc/desktop:next . &&
     docker push x11vnc/desktop:next &&
     touch success'
  # Test scripts
  - ./ubuntu_desktop.py -d -n -t next && docker stop $(docker ps -q)
  - docker images
