os: linux
dist: trusty
language: python
services: docker

env:
  - BRANCH=chrome

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml -e image -e conf)" ]] ||
     (docker build --tag x11vnc/desktop:$BRANCH . &&
      docker push x11vnc/desktop:$BRANCH &&
      touch success)'
  # Test scripts
  - 'git clone --depth 1 https://github.com/x11vnc/docker-desktop master &&
     master/ubuntu_desktop.py -d -n -t $BRANCH && docker stop $(docker ps -q)'
  - docker images
