os: linux
dist: trusty
language: python
services: docker

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - 'docker build --tag x11vnc/desktop:17.10 
                  --tag x11vnc/desktop:artful
                  --tag x11vnc/desktop:latest . &&
     docker push x11vnc/desktop &&
     touch success'
  # Test scripts
  - ./ubuntu_desktop.py -d -n -t latest && docker stop $(docker ps -q)
  - docker images
