language: python
services: docker

env:
  - BRANCH=master
  - BRANCH=14.04
  - BRANCH=zh_cn

script:
  - git clone https://github.com/x11vnc/ubuntu-docker.git master &&
    git clone -b $BRANCH https://github.com/x11vnc/ubuntu-docker.git daily &&
    docker build --tag x11vnc/ubuntu-desktop:daily daily &&
    master/ubuntu_desktop.py -d -n -t daily && docker stop $(docker ps -q)
  - docker images
