os: linux
dist: trusty
language: python
services: docker

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker build --tag x11vnc/desktop:14.04 . && docker push x11vnc/desktop:14.04
  - docker images
