os: linux
language: python
services: docker

before_script:
  - git clone --depth=1 https://$GIT_TOKEN@github.com/xmjiao/ci-util.git

script:
  - './ci-util/build-docker.sh : x11vnc/desktop:17.10-dev &&
     ./ubuntu_desktop.py -d -n -t 17.10-dev && docker stop $(docker ps -q) &&
     ./ci-util/trigger-via-api.sh'
  - docker images
