os: linux
dist: trusty
sudo: required
language: python

env:
  - REPOSITORY=compdatasci/ams595-desktop BRANCH=master

before_script:
  - git config --global user.email "xmjiao@gmail.com"
  - git config --global user.name "Xiangmin Jiao"

script:
# Update README by inserting new section for full-screen mode
  - "git clone -b $BRANCH https://$GIT_USER:$GIT_TOKEN@github.com/$REPOSITORY childrepo 2> /dev/null &&
    cd childrepo &&
    perl -0777 -e 's/## Entering Full-Screen Mode.+(\n##)/%%FULL_SCREEN_SECTION%%$1/igs' -p README.md | sed -e '/%%FULL_SCREEN_SECTION%%/ {' -e 'r .travis.yml' -e 'd' -e '}' > README.new &&
    (diff -q README.new README.md || 
     (git commit -m 'Updated README for full-screen mode' &&
      git push))"
